# picowl OpenEmbedded mini-layer (wrynose and blacksail)
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "picowl-layer"
BBFILE_PATTERN_picowl-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_picowl-layer = "6"

LAYERDEPENDS_picowl-layer = "core"
LAYERSERIES_COMPAT_picowl-layer = "wrynose blacksail"
