#!/usr/bin/env python3
"""Generates panel-pixfont-data.c, the pixel fonts of picowl-panel's crisp
style, from X11 BDF files.

    gen-pixfont.py gen OUT.c FONT.bdf...    the C data, in the order given
    gen-pixfont.py trim IN.bdf OUT.bdf      keep only printable ASCII of a BDF

The BDF files in this directory are what `trim` makes of the misc-fixed fonts
of the X.Org font-misc-misc package (as installed by Debian's xfonts-base, in
PCF form, and converted with pcf2bdf), so that the data can be regenerated
without an X font installation:

    for f in 6x10 7x13 7x13B 8x13 10x20; do
        pcf2bdf /usr/share/fonts/X11/misc/$f.pcf.gz -o /tmp/$f.bdf
        gen-pixfont.py trim /tmp/$f.bdf $f.bdf
    done
    gen-pixfont.py gen ../panel-pixfont-data.c 6x10.bdf 7x13.bdf 7x13B.bdf 8x13.bdf 10x20.bdf

The generator refuses a font whose header does not carry a COPYRIGHT line that
says "public domain", because panel/fonts/LICENSES says that is what these
files are.

Each glyph is stored as one byte per row (two, big endian, for a cell wider
than 8 pixels), the leftmost pixel in the top bit, for the characters
0x20..0x7e, in a cell of the font's bounding box with the baseline `ascent`
rows from the top.
"""
import os
import sys

FIRST, LAST = 0x20, 0x7E


def parse(path):
    font = {"props": {}, "glyphs": {}}
    cur = None
    in_props = False
    with open(path) as f:
        lines = f.read().split("\n")
    i = 0
    while i < len(lines):
        ln = lines[i]
        i += 1
        if not ln.strip():
            continue
        key, _, rest = ln.partition(" ")
        if cur is None and key == "STARTCHAR":
            cur = {"name": rest, "rows": []}
        elif cur is None:
            if key == "STARTPROPERTIES":
                in_props = True
            elif key == "ENDPROPERTIES":
                in_props = False
            elif in_props:
                font["props"][key] = rest.strip().strip('"')
            elif key == "FONTBOUNDINGBOX":
                font["bbx"] = tuple(int(v) for v in rest.split())
        elif key == "ENCODING":
            cur["enc"] = int(rest.split()[0])
        elif key == "BBX":
            cur["bbx"] = tuple(int(v) for v in rest.split())
        elif key == "BITMAP":
            for _ in range(cur["bbx"][1]):
                cur["rows"].append(int(lines[i].strip(), 16))
                i += 1
        elif key == "ENDCHAR":
            font["glyphs"][cur["enc"]] = cur
            cur = None
    return font


def check_licence(font, path):
    cr = font["props"].get("COPYRIGHT", "")
    if "public domain" not in cr.lower():
        sys.exit("%s: COPYRIGHT is '%s', not a public domain font" % (path, cr))


def cell(font, g):
    """The rows of a glyph in the font's cell: a list of 16 bit values with
    the leftmost pixel in bit 15."""
    bw, bh, bx, by = font["bbx"]
    gw, gh, gx, gy = g["bbx"]
    if bw > 16:
        sys.exit("cell wider than 16 pixels")
    asc = int(font["props"]["FONT_ASCENT"])
    nbytes = (gw + 7) // 8
    out = [0] * bh
    for r, bits in enumerate(g["rows"]):
        row = asc - gy - gh + r
        if not 0 <= row < bh:
            continue
        for x in range(gw):
            if bits >> (8 * nbytes - 1 - x) & 1:
                cx = gx - bx + x
                if not 0 <= cx < bw:
                    sys.exit("glyph %s leaves the cell" % g["name"])
                out[row] |= 0x8000 >> cx
    return out


def trim(src, dst):
    with open(src) as f:
        lines = f.read().split("\n")
    out = []
    glyph = None
    chars_at = None
    nchars = 0
    for ln in lines:
        key = ln.split(" ", 1)[0]
        if key == "CHARS":
            chars_at = len(out)
            out.append(ln)
        elif key == "STARTCHAR":
            glyph = [ln]
            keep = False
        elif glyph is not None:
            glyph.append(ln)
            if key == "ENCODING":
                keep = FIRST <= int(ln.split()[1]) <= LAST
            elif key == "ENDCHAR":
                if keep:
                    out.extend(glyph)
                    nchars += 1
                glyph = None
        elif ln:
            out.append(ln)
    out[chars_at] = "CHARS %d" % nchars
    with open(dst, "w") as f:
        f.write("\n".join(out) + "\n")


def ident(path):
    return os.path.splitext(os.path.basename(path))[0]


def gen(dst, paths):
    out = ["/* Generated by panel/fonts/gen-pixfont.py from the BDF files in panel/fonts/;\n"
           " * do not edit. The fonts are public domain, see panel/fonts/LICENSES. */\n"
           '#include "panel-pixfont.h"\n']
    tab = []
    for p in paths:
        font = parse(p)
        check_licence(font, p)
        name = ident(p)
        bw, bh = font["bbx"][0], font["bbx"][1]
        bpr = (bw + 7) // 8
        asc = int(font["props"]["FONT_ASCENT"])
        out.append("static const uint8_t rows_%s[%d * %d * %d] = {"
                   % (name, LAST - FIRST + 1, bh, bpr))
        for code in range(FIRST, LAST + 1):
            g = font["glyphs"].get(code)
            rows = cell(font, g) if g else [0] * bh
            if bpr == 1:
                vals = ["0x%02x" % (r >> 8) for r in rows]
            else:
                vals = ["0x%02x, 0x%02x" % (r >> 8, r & 0xff) for r in rows]
            out.append("\t%s /* %s */" % (", ".join(vals) + ",", repr(chr(code))))
        out.append("};\n")
        tab.append((name, bw, bh, asc, bpr))
    for name, bw, bh, asc, bpr in tab:
        out.append('const struct pl_pixfont pl_pixfont_%s = { "%s", %d, %d, %d, %d, rows_%s };'
                   % (name, name, bw, bh, asc, bpr, name))
    with open(dst, "w") as f:
        f.write("\n".join(out) + "\n")


def main():
    if len(sys.argv) >= 4 and sys.argv[1] == "gen":
        gen(sys.argv[2], sys.argv[3:])
    elif len(sys.argv) == 4 and sys.argv[1] == "trim":
        trim(sys.argv[2], sys.argv[3])
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
